In [1]:
!where python

C:\Users\daani\Anaconda3\python.exe
C:\Users\daani\AppData\Local\Microsoft\WindowsApps\python.exe


In [2]:
%load_ext autoreload
%autoreload 2

In [37]:
#Standard imports
import os
from collections import Counter
import pickle
import sys
sys.path.append('..')

#Third-party imports
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, learning_curve
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.inspection import plot_partial_dependence
from sklearn.metrics import roc_curve, roc_auc_score
from statsmodels.stats.outliers_influence import variance_inflation_factor

#Local imports
from src.localpaths import *
from src.data.make_dataset import load_training_data, load_test_data
from src.data.make_dataset import load_test_data
from src.models.train_model import store_model_and_results, print_model_results, load_model_results, load_pickled_models
from src.visualization.visualize import plot_learning_curve
from src.models.predict_model import predict

In [4]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

# Get predictions for our test data

In [31]:
y_score = predict(X_TEST_RAW_PATH, proba = True)

loading columns to drop


In [32]:
y_score

array([0.75283814, 0.10574972, 0.01530238, ..., 0.11460519, 0.76338809,
       0.27442961])

In [33]:
y_pred = [round(num) for num in y_score]

In [34]:
y_pred = [int(i) for i in y_pred]

In [35]:
y_pred = np.array(y_pred)

In [36]:
y_pred

array([1, 0, 0, ..., 0, 1, 0])

# Evaluate our predictions

In [15]:
X_test, y_test = load_test_data()

In [19]:
y_test=y_test["Churn"].map({"Yes": 1, "No": 0}).values

In [20]:
y_test

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [39]:
roc_auc_score(y_test, y_score)

0.8578950882461185